### ISSUE TITLE
Alpha version notice

### ISSUE THREAD

**Issue by modehnal** [behave-contrib/behave-html-pretty-formatter#1]
Hello @jenisys @bittner,

opening an issue just as an FYI.

This is an attempt to have an another option for html formatter _html-pretty_.

The formatter is already in functioning state - the generating works dynamically - while the images are a static example.

I am not quite happy with it yet and the project is still work in progress but I pushed it here so me and @fpokryvk can work on it and have history.

I hope you don't mind the name of the project, I tried to follow the naming convention you have here.

I will try to mimic the structure of existing projects here, please let me know if I am doing something wrong, or if I am not doing anything I should. If anything needs to be changed, let me know. Feedback is always appreciated.

Have a nice day.

**Comment by bittner** [comment]
Sounds fine to me, provided this project is significantly different from the original html formatter. Maybe just for clarification:

- Is there a reason we can't include your adaptions with the original [behave-html-formatter](https://github.com/behave-contrib/behave-html-formatter) project? (Can't we have formatter options or something?)
- The name suggest that the original formatter creates "simplistic" or "ugly" output. Is that true? (Why keep it that way?)

Just curious.

**Comment by modehnal** [comment]
@bittner I should have mentioned the branch [devel/alpha](https://github.com/behave-contrib/behave-html-pretty-formatter/tree/devel/alpha) already has images in README and code present so you can see how it looks and compares to the old one.

The reason we cannot include it is that the generation of the html is done in a very different way and maintaining both versions would not be the desired outcome.

The name indeed suggests that the original was a bit "ugly", although that is up to the personal view. The new one looks more refined and pretty, hence the name.

The reason for a new project is to reduce complexity, make it more readable and maintainable with intention of developing new features to this formatter instead of the old one, where we had to hack around a bit to get our desired features functioning.

We have visually impaired teammates so features like High Contrast as you can see in the branch I mentioned are done more easily.

This project aims to reduce work required for maintaining and developing. While improving experience as an end user of the generated page. All in all making job easier for everyone involved.

**Comment by modehnal** [comment]
I also forgot to mention, the name _html-pretty_ or behave-html-_pretty_-formatter comes from the knowledge of existing behave formatters. Since there is a formatter _pretty_, I thought the _html-pretty_ fits.

I am not against changing it so that it is not implied that one is prettier/uglier than the other.
