### ISSUE TITLE
Embed the feature description in the report

### ISSUE THREAD

**Issue by lu-maca** [behave-contrib/behave-html-pretty-formatter#24]
Hi,

is it possible to add the feature description in the report?

For example:
```
Feature: feature name
     Here I test some requirements related to some functionality...
```

Luca

**Comment by modehnal** [comment]
So while behave supports this and we could add this. The main panel with feature name is supposed to be clean and serve as a kind of divider between other features.

i suppose you want a multiline description and not a single comment under feature which could simply be used like this, correct?
`Feature: feature name: Here I test some requirements related to some functionality...`

In effect you would use this as follows?

```
Feature: feature name
     Description 1
     Description 2
     Description 3
```

**Comment by modehnal** [comment]
@lu-maca Would this be acceptable? We have come to an agreement with @fpokryvk that this does not look bad, the margins and padding can be adjusted but at least the commentary is not located in the main feature panel.

If there is a feature commentary the scenaros status will get moved to the right and commentary will take its place.
![test_image_feature_info](https://user-images.githubusercontent.com/40463522/214063945-8e10e61a-d80a-4d76-9bb7-f762e64c3d19.png)

Without any commentary the result is as usual.
![example_original](https://user-images.githubusercontent.com/40463522/214064748-e17c5255-ec84-4564-bf24-962019cd1447.png)

The commentary in feature files is done simply by 
```
@dummy
Feature: Test
  This is a test to see how big the entire space is and when the wrap will happen.
  This is another
  Hello there!
```

The behave will return the text to us from feature.description in form of a list of strings.

**Comment by lu-maca** [comment]
@modehnal this is good to me, sure!

**Comment by modehnal** [comment]
Very well, tomorrow I will do a pull request with these changes.

I have already made some cleanup we wanted to do with more coming this week. I believe this week I will have enough time to focus on this project and release 1.5 with all the changes.

**Comment by lu-maca** [comment]
Thank you @modehnal, appreciate that!
