### ISSUE TITLE
Embeded links have no space between with pretty_output=False

### ISSUE THREAD

**Issue by fpokryvk** [behave-contrib/behave-html-pretty-formatter#28]
```python
embed("link", [(link1, label1), (link2, label2)], "Links")
```

This will result to the following after embed is expanded, if pretty output is turned off:

Links
&nbsp; [label1](http://link1)[label2](http://label2)

With pretty output there is space between, but maybe newline would be better.

**Comment by modehnal** [comment]
I agree.
