### ISSUE TITLE
Try to make sure the generated page is valid xml

### ISSUE THREAD

**Issue by modehnal** [behave-contrib/behave-html-pretty-formatter#33]
xml validator seems to have issues with the generated page. Try to look into it.

There is a use case where someone might want to load the page with xml parser.

**Comment by fpokryvk** [comment]
I would suspect `pretty_output=False` option, but I will investigate further.

**Comment by fpokryvk** [comment]
Test

**Comment by modehnal** [comment]
Test Slack Comment

**Comment by fpokryvk** [comment]
I have checked python `lxml` module, it indeed can't parse the file as xml, throwing error at weird position (somewhere in the middle of minified javascript with `pretty_output=False`), however, `lxml.html` module works fine even with condensed output. Or did you have some more specific issues in mind? @modehnal Is this safe to close?

**Comment by modehnal** [comment]
We can close this. I believe this issue was raised by our colleague who wanted it for some specific use case that was solved or is not needed anymore, I am not sure now it was quite some time back.
