### ISSUE TITLE
Bug: wrong status assignment

### ISSUE THREAD

**Issue by lu-maca** [behave-contrib/behave-html-pretty-formatter#36]
Hi guys,

a colleague of mine found a bug that makes the formatter crash.

https://github.com/behave-contrib/behave-html-pretty-formatter/blob/a0920ca87b32de4fed3ed64f6895a44c89ad2337/behave_html_pretty_formatter/html_pretty.py#L301

Line 301 shall be:
` self.status = self._scenario.status.name`
and not
`self.status = self._scenario.status`

**Comment by modehnal** [comment]
Thanks for the report.

It is weird I have not seen it in our automation yet as I have tested quite a lot of scenarios already but I should have for sure.

There is an issue with the contents of the `.status`. As I went over the code, I can see we use both `Status.failed` and `Status.failed.name`.

**Comment by modehnal** [comment]
@lu-maca Can you test Filip's changes? On my side all works well but since I did not see the issue before I will wait for your confirmation.

Once we have the confirmation I will do the merge and build the new version to fix the bug.

**Comment by nic-franz** [comment]
Hi guys,
I am @lu-maca 's colleague (and also a new subscriber to GitHub!) I confirm that your solution solves the problem.
Thank you all!

**Comment by modehnal** [comment]
@nic-franz Welcome and thank you for your confirmation. Version 1.8 is ready to be used from pypi.

**Comment by lu-maca** [comment]
@modehnal thanks guys :)
