### ISSUE TITLE
Choose the extension of a downloadable file

### ISSUE THREAD

**Issue by lu-maca** [behave-contrib/behave-html-pretty-formatter#38]
Hi guys,

is it possible to choose the extension of the file downloadable by "Download" button in embed data?
I'm quite sure the answer is: no, at the moment. 

One solution should be to add a check to the filename. 
If the pattern ".something" is present in the filename, do nothing; if not, append .txt to it.

A basic implementation: in `function download_embed(id, filename)`:
```javascript
if (tag === "span") {
  if (filename.search("(\\.\\w+)") == -1){
    filename += ".txt";
  }
  value = "data:text/plain," + encodeURIComponent(decodeHTMLEntities(child.innerHTML));
```
This shall also be done for other branches, but I'm not sure if this works for non text files. Also, I'm not sure if this is the best  workaround for this problem.

Thanks
Luca

**Comment by fpokryvk** [comment]
Hi,

currently the answer is no, filename is fixed to be embed caption and extension is appended by `mime_type` of embed. We can add the following support for this:

* call `formatter.embed(..., caption="Something zipped", filename="something.zip")` - we probably need to add support for binary files as well, if not done yet (I do not remember)
* call `formatter.embed(..., caption="something.zip")`
* if extension is not recognized (no filename and no 'dot' in caption), then the default is added.

Thanks for raising this!

**Comment by lu-maca** [comment]
This looks good to me!
