### ISSUE TITLE
Summary timestamps: show one of them always, use YYYY-mm-dd

### ISSUE THREAD

**Issue by djasa** [behave-contrib/behave-html-pretty-formatter#45]
* Sometimes it's very handy to see right away how old the report is, so one of the start/finish time stamps could be in `feature-title` box (start seems better to me)
* Dates are currently printed in 00-00-YYYY format that's prone to misreadings, display them in YYYY-mm-dd (+TZ) instead, please

**Comment by fpokryvk** [comment]
This is all configurable in behave.ini, just change the following 2 values as you wish:

```ini
[behave.userdata]
...
# The '%' must be escaped in ini format.
behave.formatter.html-pretty.date_format = %%d-%%m-%%Y %%H:%%M:%%S
# Defines if the summary is expanded upon start.
behave.formatter.html-pretty.show_summary = false
```

**Comment by modehnal** [comment]
So the start/finish timestamps are not visible by default as that does not seems like an important part of the test report, but that is a personal opinion. We can talk about this in the next update if that is something we should add perhaps as you say to the feature title, while the summary is collapsed.

But in the meantime if you require the start date to be seen on first open of the report consider using option in the [behave.ini](https://github.com/behave-contrib/behave-html-pretty-formatter/blob/main/behave.ini#L17C1-L17C50) will make sure the summary is always open:
`behave.formatter.html-pretty.show_summary = true`

For the date format please take a look at [behave.ini](https://github.com/behave-contrib/behave-html-pretty-formatter/blob/main/behave.ini#L15).

You can define your desired date format in your projects. Which in your case would look like this:
`behave.formatter.html-pretty.date_format = %%Y-%%m-%%d`

**Comment by modehnal** [comment]
Closing the issue for now as the formatter provides a possibility to change date format and date appearance in the behave.ini file as you requested without any need to change something on the formatter side.

**Comment by djasa** [comment]
> We can talk about this in the next update if that is something we should add perhaps as you say to the feature title, while the summary is collapsed.

I stumbled upon this when going through a pile of reports which didn't have obvious timestamp until opening and I wanted to know if I'm looking at something fresh or something from a long time ago, for which a single time stamp visible by default would be very helpful while not cluttering the design (IMO). OTOH keeping detailed info collapsed by default is OK.

**Comment by modehnal** [comment]
> I wanted to know if I'm looking at something fresh or something from a long time ago

That is indeed a good point and would be useful to others as well. I will look into it.

**Comment by modehnal** [comment]
@djasa Would this be acceptable? It has the same format as the behave.ini definition so you can define whatever format you would like. 
![date_format_in_header](https://github.com/behave-contrib/behave-html-pretty-formatter/assets/40463522/3b9236d3-f73f-49eb-b3e5-576635f32210)

**Comment by modehnal** [comment]
Alright, the change is simple enough. It will be in the next released version. https://github.com/behave-contrib/behave-html-pretty-formatter/commit/07be9433d88742c07238ff554fceec08725659ef

**Comment by modehnal** [comment]
Added in #47
