### ISSUE TITLE
Custom setting to expand or collapse the default reporting scenarios

### ISSUE THREAD

**Issue by jmv74211** [behave-contrib/behave-html-pretty-formatter#51]
Hi,

The default behavior when opening the report HTML file is that all scenarios are shown expanded. I know there is a button to collapse them all, but I would like to ask or propose (in case it is not implemented) if we can modify the default behavior in some way.

In my case, I would like that when I open the report, by default everything appears collapsed.

In case there is no option to configure this behavior (as for example there is to show the summary), I would like to request it as an improvement.

Thanks 😄

**Comment by fpokryvk** [comment]
Hi,
of course, we can implement something, I would propose "collapse_all" in configurable in behave.ini (similar to already existing "show_summary"). Thanks for good idea for improvement. Maybe, it would be nice to do callapse_all when there are many scenarios (let's say more than 10), but that is for another discussion.

**Comment by bittner** [comment]
What about `collapse = all` (default `none`)?

That would leave further enhancements open and probably easy to implement via values of the option.

**Comment by fpokryvk** [comment]
Sure, that also works. I will look into it tomorrow.

**Comment by jmv74211** [comment]
Thanks, I saw that this is already available in 1.10 🚀
