### ISSUE TITLE
Adding a button to toggle between dark/light mode

### ISSUE THREAD

**Issue by abdullahsaf** [behave-contrib/behave-html-pretty-formatter#54]
Hi,

The current behavior of the package displays the generated HTML report based on the user's browser settings, which can result in it being styled in dark mode if that's the user's preference. I would like to suggest the addition of a button, similar to a high contrast button, that allows users to easily toggle between light and dark modes.

Thanks.

**Comment by fpokryvk** [comment]
Hi,
thank you for suggestion of impovement. I would like to have a release done next week, this seems possible to be included in the release. For me it works to switch automatically by sunset/sunrise, but I understand that switch button might be handy.
