### ISSUE TITLE
How to get only the latest run of same scenario ? 

### ISSUE THREAD

**Issue by malindajudo** [behave-contrib/behave-html-pretty-formatter#63]
Sorry I want to ask question rather reporting an issue, 
We are using behave-html-pretty-formatter in our tests, and it is producing the required nice report. For some testing, though, we have the retry option activated. If a test fails, it will attempt to perform the same test it a maximum of three times.  In such instance, the report displays all three attempts' pass/fail statuses. 

E.g. 
Scenario: user can read the email
1st attempt : Failed 
2nd attempt : Failed 
3rd attempt : Passed 

Is it possible to include the status of the most recent(last) attempt in the report? We are aware that this needs to be customised, but we're not sure where or how to do it. Many thanks if you could help.

**Comment by modehnal** [comment]
Can you show us how you started the behave run? 

We are also using the retry option for some suites but we are using one report page for one test so issue like this will never happen since the generated page will be discarded and overwritten with another attempt.

I am not sure how that can happen to be honest so extra information will be required.

**Comment by modehnal** [comment]
Also perhaps explain what retry option means in your use case since we can have very different implementation. (edit: I would assume this is where the issue will be, perhaps I am not understanding what you mean by this)

**Comment by modehnal** [comment]
I think I see what you mean now. I looked in the behave and they have auto-retry option. Is that what you are using? 

We have our own retry option wrapped over the behave execution.

**Comment by modehnal** [comment]
@malindajudo I now understand what you meant.

I had no idea the auto retry option even existed so thank you for the idea.

I have implemented the hiding of the previous attempts in this [commit](https://github.com/behave-contrib/behave-html-pretty-formatter/compare/main...modehnal/show_retry_attempts) so please try it out and let me know if this is what you need.

To test it I needed to include this part in my `environment.py` file as is in the auto-retry documentation and of course tagging the appropriate scenarios in `feature` file.

```python
from behave.contrib.scenario_autoretry import patch_scenario_with_autoretry
def before_feature(context, feature):
    for scenario in feature.scenarios:
        if "autoretry" in scenario.effective_tags:
            patch_scenario_with_autoretry(scenario, max_attempts=2)
```
The default value is `true` so the value missing or having it in your `behave.ini` file will generate the page as expected:

```ini
behave.formatter.html-pretty.show_retry_attempts = true
```
![show_retry_attempts](https://github.com/behave-contrib/behave-html-pretty-formatter/assets/40463522/3fe988b5-c88e-4265-9d28-28acd0a72107)

And when you disable it as follows, it will no longer generate previous attempts.

```ini
behave.formatter.html-pretty.show_retry_attempts = false
```
![show_retry_attempts_false](https://github.com/behave-contrib/behave-html-pretty-formatter/assets/40463522/fb1ede78-183e-4488-ae79-c5753d351f3b)

I also attempted to make an improvement to the Scenario name strings with "Scenario: name - retry attempt #" but that did not look good to me so I am not including it as of now. We might consider to add that in the future.

**Comment by malindajudo** [comment]
> I think I see what you mean now. I looked in the behave and they have auto-retry option. Is that what you are using?
> 
> We have our own retry option wrapped over the behave execution.

Yes Michal , we are using the behave auto-retry option

**Comment by malindajudo** [comment]
> @malindajudo I now understand what you meant.
> 
> I had no idea the auto retry option even existed so thank you for the idea.
> 
> I have implemented the hiding of the previous attempts in this [commit](https://github.com/behave-contrib/behave-html-pretty-formatter/compare/main...modehnal/show_retry_attempts) so please try it out and let me know if this is what you need.
> 
> To test it I needed to include this part in my `environment.py` file as is in the auto-retry documentation and of course tagging the appropriate scenarios in `feature` file.
> 
> ```python
> from behave.contrib.scenario_autoretry import patch_scenario_with_autoretry
> def before_feature(context, feature):
>     for scenario in feature.scenarios:
>         if "autoretry" in scenario.effective_tags:
>             patch_scenario_with_autoretry(scenario, max_attempts=2)
> ```
> 
> The default value is `true` so the value missing or having it in your `behave.ini` file will generate the page as expected:
> 
> ```ini
> behave.formatter.html-pretty.show_retry_attempts = true
> ```
> 
> ![show_retry_attempts](https://private-user-images.githubusercontent.com/40463522/286224988-3fe988b5-c88e-4265-9d28-28acd0a72107.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMTM5NDcsIm5iZiI6MTcwMTIxMzY0NywicGF0aCI6Ii80MDQ2MzUyMi8yODYyMjQ5ODgtM2ZlOTg4YjUtYzg4ZS00MjY1LTlkMjgtMjhhY2QwYTcyMTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDIzMjA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNGZiYWNmMWY4MTUxMDJkYjFmZTkyMGU0ZThiMjllN2E0MzcyOWM0Yzc1ZDEwMjJlODJkMTU1OTI0YmJlNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hsegfsejL_6yDsJC962x5tMxp6-L5O4kBRJs3hXHNQU)
> 
> And when you disable it as follows, it will no longer generate previous attempts.
> 
> ```ini
> behave.formatter.html-pretty.show_retry_attempts = false
> ```
> 
> ![show_retry_attempts_false](https://private-user-images.githubusercontent.com/40463522/286225089-fb1ede78-183e-4488-ae79-c5753d351f3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMTM5NDcsIm5iZiI6MTcwMTIxMzY0NywicGF0aCI6Ii80MDQ2MzUyMi8yODYyMjUwODktZmIxZWRlNzgtMTgzZS00NDg4LWFlNzktYzU3NTNkMzUxZjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDIzMjA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5N2I2Y2QyYTA3NTIzZjJhYWJlMmNjZjA4YTlkOWVkM2ZlNmE2ZmQxMjdjZDdmNmUyODcxYTVkMmY1MjAyOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QnqxCkO4KNw7yuBtxDBnxX80N-61O7B2WuufA1ooFEA)
> 
> I also attempted to make an improvement to the Scenario name strings with "Scenario: name - retry attempt #" but that did not look good to me so I am not including it as of now. We might consider to add that in the future.

Thanks a lot for this @modehnal , This is exactly what I want.  This fix has not been released yet right ? To test I have to fork the repo I guess.

**Comment by modehnal** [comment]
> Thanks a lot for this @modehnal , This is exactly what I want. This fix has not been released yet right ? To test I have to fork the repo I guess.

Yeah please do and verify the changes are working for you. (or you can simply clone the repository and copy the file content to its location)

Once you do I will make a minor release with this fix/feature.

**Comment by modehnal** [comment]
Made a few minor changes which you can see in [commit](https://github.com/behave-contrib/behave-html-pretty-formatter/compare/main...modehnal/show_retry_attempts)

Main change is improving the the comparison with integers instead of strings

**Comment by malindajudo** [comment]
@modehnal , thanks for the details . I have tested this. What I did is , 
Cloned the repo --> Manually add your commit changes. 
Then ran the tests from 'behave_html_pretty_formatter' repo giving the feature files location. 

Executed cmd is 

`~/Source/behave-html-pretty-formatter (main)
$ behave -f behave_html_pretty_formatter:PrettyHTMLFormatter -o auto-report.html  C:/Users/<user>/Source/test-automation-project/features/run_format_test.feature`

However still I see the retry scenario details in the report, 

Frist I tried adding following to behave.ini in my project. But same results. 
behave.formatter.html-pretty.show_retry_attempts = false

Then I change this location to false. But same results 
https://github.com/behave-contrib/behave-html-pretty-formatter/compare/main...modehnal/show_retry_attempts#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R86

May be I am not running your changes correctly. Is it possible to get beta release then I can check or please let me know any other suggestions. Thanks a lot 

![image](https://github.com/behave-contrib/behave-html-pretty-formatter/assets/131215042/d802a55d-605a-4dc7-9de8-7825654d2360)

**Comment by modehnal** [comment]
I have no experience with this project on the Windows so I do not know how to properly do local changes but that seems like the most likely reason why it is not working for you.

I made the test release to pypi so you can test the changes
https://test.pypi.org/project/behave-html-pretty-formatter/1.10/

**Comment by malindajudo** [comment]
Thanks for the support @modehnal , I install the version 1.10 but still same results. Still showing the retry attempts even when following is already added to the behave.ini 
_behave.formatter.html-pretty.show_retry_attempts = false_

Please need your help. Thanks

**Comment by modehnal** [comment]
It appears we are in quite a different timezone, having a single interaction per day is unfortunate.

For the debugging I will really need more information from you.

I have nothing to start with.

First make sure it is really updated. Make a list from your system and look up what version is installed.

Just to be sure uninstall the released one and install the test.pypi one. Make sure there is only one of those on your system. There can be multiple if they were installed with different permissions.

If all of these look good. Locate the actual `html_pretty.py` file in you system and verify that the code is in place.

Then please show me how looks your entire `behave.ini` file, there can be an issue in different part that can mess things up.

Make sure the `behave.ini` file is in correct place. You can try changing the title `behave.formatter.html-pretty.title_string = DUMMY TITLE` to make sure that your `behave.ini` file has an effect on your runs.

After that, how does your exact behave execution line looks? Because if I use your line 
>$ behave -f behave_html_pretty_formatter:PrettyHTMLFormatter -o auto-report.html 

It works for me without any issue.

I can see no other issues here. Apart from the system I have tried the new package myself multiple times on different machines and it works.

Hopefully something above will solve the issue.

**Comment by malindajudo** [comment]
Thanks for the reply, Let me check this in a fresh instance in our CI pipeline. Get back to you very soon.

**Comment by malindajudo** [comment]
Hi @modehnal , After I uninstall the older version , I can confirm I only see the latest execution details in the report. 
Thanks for your support much appreciated. Hope you will release this fix asap so we can use it.

**Comment by modehnal** [comment]
@malindajudo So the PR is open and hopefully today we will merge it and build a new version.

Thank you for opening the issue. We have learned some things too and improved our own suites with new features!

Apart from the **auto-retry** one of our teammates gave me another idea how to use the patch function - **stability**. Which is exact opposite of the auto-retry. The **stability** will run number of tests and all of them have to pass or it will fail. The original patch cannot be used as is, so I am currently using my own patch and not the one from behave.

Then with a bit of "hacking" I hooked those functions to behave's **before_feature** and I tied it all to the **tags** so that we can tag the scenarios with for example **`@autoretry=3`** or **`@stability=5`**.

Now we can define number of retries in feature files.

**Comment by modehnal** [comment]
New version [1.10.2](https://pypi.org/project/behave-html-pretty-formatter/) is built.

**Comment by malindajudo** [comment]
> @malindajudo So the PR is open and hopefully today we will merge it and build a new version.
> 
> Thank you for opening the issue. We have learned some things too and improved our own suites with new features!
> 
> Apart from the **auto-retry** one of our teammates gave me another idea how to use the patch function - **stability**. Which is exact opposite of the auto-retry. The **stability** will run number of tests and all of them have to pass or it will fail. The original patch cannot be used as is, so I am currently using my own patch and not the one from behave.
> 
> Then with a bit of "hacking" I hooked those functions to behave's **before_feature** and I tied it all to the **tags** so that we can tag the scenarios with for example **`@autoretry=3`** or **`@stability=5`**.
> 
> Now we can define number of retries in feature files.

Thanks for your support @modehnal , is it possible to get the code that you implement for this **`@autoretry=3`** or **`@stability=5`**. This is fantastic , because every our tests have to retry with the same number of attempts. 
I need to do more investigation about  'stability' , Thanks for the info

**Comment by modehnal** [comment]
Of course. The commit with the code is here https://gitlab.com/dogtail/qecore/-/commit/2a2306ad459b09b138a34df336aa58bc071ee630

**Comment by malindajudo** [comment]
> Of course. The commit with the code is here https://gitlab.com/dogtail/qecore/-/commit/2a2306ad459b09b138a34df336aa58bc071ee630

Thanks a lot

**Comment by malindajudo** [comment]
@modehnal , I tested with the released version , for some reason I don't see this fix is working. I installed the latest from 
https://pypi.org/project/behave-html-pretty-formatter/ 

Running the cmd 
`pip install behave-html-pretty-formatter`

Could you please check from your end ? Thanks a lot

**Comment by modehnal** [comment]
Nothing has changed from the test version. Try the same steps I recommended to debug it.

On my side I removed all of my custom setup and used just the behave patch for autoretry and all works as expected.

Best practice is to fix the version you want to prevent issues with future versions. So install it like this `pip install behave-html-pretty-formatter==1.10.2`
