### ISSUE TITLE
Add global summary to the HTML report when running multiple features in the same test execution

### ISSUE THREAD

**Issue by jmv74211** [behave-contrib/behave-html-pretty-formatter#65]
Hi,

I want to propose an HTML report improvement when running multiple features.

When running multiple feature files, the report summary does not show the global results but only shows each scenario summary. For instance:
![image](https://github.com/behave-contrib/behave-html-pretty-formatter/assets/23462183/ae2c00d5-f0cf-4f08-9ed8-1d71ae56a182)

In this case, the global test results are:

```
15 features passed, 3 failed, 0 skipped
160 scenarios passed, 6 failed, 42 skipped
1299 steps passed, 3 failed, 375 skipped, 0 undefined, 22 untested
Took 115m9.222s
```

It would be nice if the global info would appear at the top of the report. This will show if all tests have passed without scrolling the entire report to analyze each feature scenario results. 

On the other hand as a secondary aspect, regarding the global "took time", instead of being calculated as the sum of each scenario time, it is calculated from the start until the end of the testing session, because there are preconditions and postconditions that are run between scenarios that are not being taken into account (for example, in the above example It shows 115m but it is ~150min). I don't know if this is possible to set at the report level or it will have to be calculated in runtime and overwrite the report data.

Thanks 😄

**Comment by modehnal** [comment]
Hi,

we have some changes planned for multi-feature runs in the future as can be seen in #26. 

We will not be able to do so this year though. Starting next year we will look into this more and try to figure out a proper solution.

I am not sure how accurate the global times are as that time is from `behave` which also prints it. On our side we are counting the time with `datetime.now()` at start and at the end, which means that once we do summary for the multiple features run it should by default be in raw time it took - in your case 150 minutes.

Thank you for using our formatter.

**Comment by fpokryvk** [comment]
Hi,

if you look at #9, there are some screenshots how I wanted to improve the summary for scenarios per feature - the bar graph, where the width of the bars is dependent on the time spent in scenario, so it is nicely visible if some scenario takes too much time compared to others. However, I am not sure, how it would cope with many scenarios per feature and someone might find it confusing. There is also possibility to make the length of the bars of the same length, but that carries less information, but maybe more useful with too many scenarios, but not sure what the threshold would be (maybe we can make that configurable in `behave.ini`).

That would be per feature basis, but we can add the same for global summary (or global stats) - showing global stats of passed/failed features + the bar representation of the features based on elapsed time. All of this would be auto shown/hidden, based on number of features and scenarios per feature by default (and configurable in `behave.ini`) - if the feature is single-scenario, duration graph makes no sense, if there is only one feature in the report, it also makes no sense to show global stats by default. 

Adding "true" time spent is also good to have feature, and global stats is probably the right place for it, so will will add it with global stats. For features, steps and scenarios we rely on data from behave objects, which I suppose ignore duration of `before_*` and `after_*` hooks for some reason (that functions are also user implemented, so I think it makes no sense to exclude them from timing, but it is default of behave, so we do not change it to keep consistency with other formatters).

I am quite busy now, but I can look into it hopefully during winter holidays.

Thank you for reporting this!

**Comment by modehnal** [comment]
@jmv74211 Just in case github did not send you a notification. Please take a look at the open PR and images attached. Let us know if that will do.

**Comment by jmv74211** [comment]
Hi @modehnal, 

It looks great!

![image](https://github.com/behave-contrib/behave-html-pretty-formatter/assets/23462183/6add0924-c186-4636-a096-1096270d08f3)

Thanks for the effort 😄.
