### ISSUE TITLE
Logging without context.embed

### ISSUE THREAD

**Issue by abdullahsaf** [behave-contrib/behave-html-pretty-formatter#69]
Hi,

I recently started using the formatter and love it. The question I have is for logging when not using the html formatter (using IDE). 

The way I do it rn is:
#context.html_formatter = True if I am using this formatter else False and context.logger (using logging) is set in before_all hook
context.embed(mime_type="text/plain", data="\<string\>", caption="Text") if context.html_formatter else context.logger.info("\<string\>") 

let me know if there is a more elegant way for this

**Comment by fpokryvk** [comment]
Hi,

thank you for using formatter!

If you are using this setup:
https://github.com/behave-contrib/behave-html-pretty-formatter?tab=readme-ov-file#basic-embedding-setup---save-embedding-function-to-context

It sets `context.embed()` only if `html-pretty` formatter is present. You can tweak that following way:

```python
for formatter in context._runner.formatters:
    if formatter.name == "html-pretty":
        context.embed = formatter.embed

if not hasattr(context, "embed"):
   def _embed(mime_type, data, caption):
       context.logger.info(caption)
       context.logger.info(data)
   context.embed = _embed
```

This way you call just `context.embed()` from everywhere in the code and it either logs or embeds depending on the formatter used.

Hope this helps.

**Comment by abdullahsaf** [comment]
Thanks for updating the readme
