### ISSUE TITLE
Error if data has no len with mime_type text/*

### ISSUE THREAD

**Issue by Kory291** [behave-contrib/behave-html-pretty-formatter#74]
If you try to add data with a mime_type of `text/*` and data is `None` an error is thrown. The error message is:

> Exception TypeError: object of type 'NoneType' has no len()

This will result in the whole report not being generated, which is annoying for test runs that take a bit longer.

Maybe for clarification, is this an intended behaviour and should the user of the formatter ensure that only strings are passed, when using `text/*` as mime_type?
Otherwise would it be possible to change it, so that the report uses an empty string as default for data of type `text/*` ? This way the report would always be generated.
If so, I would open a pull request with a change for that.

Many thanks :)

**Comment by modehnal** [comment]
Thanks for the report.

While we indeed validate our inputs when using text mime type, this is not a desired outcome.

Me and @fpokryvk agreed on the fix c2bcdfa 

If you had something else in mind let me know but as of now this seems to work well and your use case was handled, you will receive your embed with "None" in the data after expanding it.

**Comment by Kory291** [comment]
This works for me. Thank you :)

**Comment by modehnal** [comment]
Issue was fixed by #75 tag was pushed, new version will be in pypi shortly.
