### ISSUE TITLE
adding <script>-tags to the report

### ISSUE THREAD

**Issue by Kory291** [behave-contrib/behave-html-pretty-formatter#77]
This is more like a general question:
I tried to embed some plots which use plotly.js but they didn't load in the report, because embedded `<script>`  tags are not loaded in the html report.
Is there any way to change this? Otherwise I would rely on the download functionality in the report.

**Comment by modehnal** [comment]
Can you provide some example as to what you are trying? I would attempt to embed with mime type `text/html` but without an example I am just guessing.

**Comment by Kory291** [comment]
I did for example the embed the following:
`context.formatter.embed(data="<script>alert('Hello there');</script>", mime_type="text/html", caption="Some data")`

If it matters to you, I could also provide a small example with plotly, but this is the same behaviour.

**Comment by fpokryvk** [comment]
We should probably add support to custom headers in this case. We should probably make this configurable in `behave.ini`, would that option work for you?

```
behave.formatter.html-pretty.custom_html_headers = path_to_file.html
```

I would prefer separate file to be inserted, as parsing tags in config file might be a challenge. The content of the `path_to_file.html` would be in `<head>`-tag. You can define local copy of the script there, or simply source them, if you don't care about self-contained HTML report.

**Comment by fpokryvk** [comment]
Can you try to manually edit some existing report and sourcing the ploty in head, if it would work then? If not, we would have to come up with something else.

**Comment by fpokryvk** [comment]
After looking at ploty.js documentation, I think proposed solution above (to include ploty library) togerher with the following code might work:
```python
graph_script="TESTER = document.getElementById('tester'); Plotly.newPlot( TESTER, [{ x: [1, 2, 3, 4, 5], y: [1, 2, 4, 8, 16] }], { margin: { t: 0 } } );"
context.formatter.embed(data=f'<div id="tester" style="width:600px;height:250px;" onclick="{graph_script}">Load the graph by click</div>', caption="Graph", mime_type="text/html")
```
that adds one extra click to load the graph, however maybe we can add `mime_type="text/script"` that would try to execute given script. I tried `onload` instead of `onclick` but browsers seems to ignore that event.

**Comment by Kory291** [comment]
I generated the plot via [Plotly write html](https://plotly.com/python-api-reference/generated/plotly.graph_objects.Figure.html#plotly.graph_objects.Figure.write_html).
Adding just the script tag to report by hand, worked for me.

So personally I'd like to have a `mime_type="text/script"` which then just receives the script tags, or the content of the script tags.

**Comment by fpokryvk** [comment]
After discussions with @modehnal, we agreed on the following solution:
* no change of behave.ini is reuqired
* add formatter API call to add custom HTML header `formatter.add_html_head_element(str_data)`

This alongside with additional fixes of HTML and compress embeds in yet unmerged 58b16c856e6cd96740626ea9612150f606557a3b results in the following working code:
```python
    context.formatter.add_html_head_element('<script src="https://cdn.plot.ly/plotly-2.35.2.min.js" charset="utf-8"></script>')

    graph_js = \
"""
TESTER = document.getElementById('tester');

TESTER.innerHTML = '';

Plotly.newPlot( TESTER, [{

x: [1, 2, 3, 4, 5],

y: [1, 2, 4, 8, 16] }], {

margin: { t: 0 } } );
"""

    context.formatter.embed(
        data=f'<div id="tester" style="width:600px;height:250px;"></div><script>{graph_js}</script>',
        mime_type="text/html",
        caption="Graph",
        compress=False,
    )
```

The script in HTML is loaded with the page, when `compress=False` is used - with `compress=True` the following embed would work (the data are decompressed by javascript, so the code execution must be event based to `onclick`):

```python
...
    graph_js = graph_js.replace("\n","").strip()
    context.formatter.embed(
        data=f'<div id="tester" onclick="{graph_js}" style="width:600px;height:250px;">Click to load the graph.</div>',
        mime_type="text/html",
        caption="Graph",
        compress=True,
    )
```

@Kory291 Please, let me know if proposed solution would work for you. If so, I will prepare pull request and we can release it soon.

**Comment by Kory291** [comment]
@fpokryvk this works for me!

**Comment by modehnal** [comment]
Tag 1.12 was created and pushed, updated version should be in pypi shortly. Please give it a try.

**Comment by Kory291** [comment]
It works. Many thanks for your support :D
