### ISSUE TITLE
Use colors in the global summary Feature/Scenario section

### ISSUE THREAD

**Issue by Cuslika** [behave-contrib/behave-html-pretty-formatter#82]
Would that be a possibility, to use the same color scheme in the Global summaries, as it is used in the Feature summary?

![image](https://github.com/user-attachments/assets/38751264-d36a-47b6-ac3f-ca91224773fb)

**Comment by modehnal** [comment]
Hello, I do not see a reason why that would not be possible. Either I or Filip will look into it once we have some time.

**Comment by fpokryvk** [comment]
Should be fairly simple, I will look into it. Thank you for report.

**Comment by modehnal** [comment]
@Cuslika Just to be clear, you meant to color it whole like this?
![color_scheme_global_summary_passed](https://github.com/user-attachments/assets/7cb27081-38a2-4c79-89a0-37ecfa04f11f)
![color_scheme_global_summary_failed](https://github.com/user-attachments/assets/6df004ff-cb07-4486-8bba-54bb431201c4)

Or did you mean to color it word by word like this?
![color_scheme_global_summary_detailed](https://github.com/user-attachments/assets/90a20272-b469-41cd-8035-d594fe81538a)

**Comment by Cuslika** [comment]
I think it would be the most ideal, to have it colored word by word, so the last one.

**Comment by modehnal** [comment]
@Cuslika For now the logic is done and I am happy with it for the moment. Filip will review this tomorrow and we should also be able to release it as well once we merge it.

If you would like to try it before the merge, you can patch your local files, the [devel/issue-82](https://github.com/behave-contrib/behave-html-pretty-formatter/compare/main...devel/issue-82) branch as is now works well. I tested a few scenarios.

**Comment by modehnal** [comment]
**Looks well on my scenarios.**
![color_scheme_global_summary](https://github.com/user-attachments/assets/0ea9d4cd-1ca5-42ed-a5be-2c58866f23cf)
**Failed Feature.**
![color_scheme_global_summary_fail](https://github.com/user-attachments/assets/10232196-697e-4984-acc9-9185c543ca3d)
**High Constrast is still respected.**
![color_scheme_global_summary_contrast](https://github.com/user-attachments/assets/c3ccb851-f471-42e7-b598-6885398818d2)

**Comment by Cuslika** [comment]
Thank you for your fast response, and work!

**Comment by modehnal** [comment]
Tag was pushed and formatter is now available in pypi with version `1.12.3`
