### ISSUE TITLE
Summary format

### ISSUE THREAD

**Issue by fpokryvk** [behave-contrib/behave-html-pretty-formatter#9]
It would be good to show summary if all following condition holds:

* there are multiple scenarios
* at least one scenario is non-passed

Also, position of date in summary is unfortunate, maybe align it right?

**Comment by modehnal** [comment]
I agree, "Duration" and "Started" could be in its own section aligned right to not get in a way of Summary data of passed/failed tests.

**Comment by lu-maca** [comment]
> Hi @lu-maca,
> 
> We have #9 to track this. Feel free to leave a comment there. I still do not know how to properly format the summary section. There are multiple possible approaches, the following seems best to me:
> 
>     * Add new section common for all features (start time, total time elapsed, additional info)
> 
>     * Summary will be just counters of scenarios and expand buttons
> 
> 
> Also, maybe we should leave `[Summary]` in every feature header to have the toggle closer.

@fpokryvk, my idea is quite the same. 
When a lot of feature are being tested - and this is the case we have in my company, it could be great to add at the header of the page (below the new "general" section)  an expandible section with a summary about each feature (for example progress bars with pass/total percentage, time per feature,...) and on each line of the summary (in my mind a line represents a feature) a link to the actual feature.

Not sure if my description is clear enough, if not I will prepare an example.

**Comment by fpokryvk** [comment]
Hmm, maybe we could get rid of `[Summary]` button completely, and make it collapsible similar to the scenario header (with small arrow prefix, feature name would serve as toggle). Summary may contain 3rd column with date and duration, and in the first summary additional info about tester.

Another idea is to get rid of collapse/expand buttons, we can make the counts clickable, and collapse/expand scenarios of given status. That might give much cleaner look to the section. 

@lu-maca Can you provide the list of stats, you would like to track and include?

**Comment by fpokryvk** [comment]
@lu-maca: by progress would you mean something like:

```
Passed: 2  (.)
Failed: 2  (/)
Skipped: 1 (-)
 
Scenarios by time:
............-----/////////................................................................./////////////////
```
where .-/ represent different statuses by colors? That might look cool for complex features with many scenarios.

**Comment by fpokryvk** [comment]
That was quicker done than I expected, it looks good in my opinion:

![image](https://user-images.githubusercontent.com/41154041/209948495-3890fee4-2072-4951-9cbd-00bb2c7c13fe.png)

The strips are clickable and points to correct scenario, even scenario name is shown on hover. I will add patch to my branch.

Now, each scenario has its own part of a strip, or did you mean to show one strip per scenario status?

**Comment by fpokryvk** [comment]
Here is how it looks with more passing scenarios:
![image](https://user-images.githubusercontent.com/41154041/209949255-9d7bbe7c-6a42-4003-83f9-0d297a2e0651.png)

**Comment by lu-maca** [comment]
I was thinking something like:

---------------------------------------------------------------------------
Test title: **test**
---------------------------------------------------------------------------
Additional info:
- info 1: ...
- info 2: ...
- ...
---------------------------------------------------------------------------
Summary of the features:
- line: Feature **foo**  -- total -- executed -- progress bar (passed green/failed red/skipped grey...)|====70%====......| -- elapsed time: N min M sec -- some other metrics/utilities(1)
- line: Feature **bar** -- total -- executed -- progress bar (passed green/failed red/skipped grey...)|====70%====......| -- elapsed time: N min M sec -- some other metrics/utilities(1)
- ...

==========================================
Feature: **foo** 
... as it is 

---------------------------------------------------------------------------
Feature: **bar** 
... as it is 

---------------------------------------------------------------------------

(1) for example related with SW requirements or user defined utilities (is it possible?). 

Edit: each line in the summary of the features could also have a "goto" button

**Comment by lu-maca** [comment]
> That was quicker done than I expected, it looks good in my opinion:
> 
> ![image](https://user-images.githubusercontent.com/41154041/209948495-3890fee4-2072-4951-9cbd-00bb2c7c13fe.png)
> 
> The strips are clickable and points to correct scenario, even scenario name is shown on hover. I will add patch to my branch.
> 
> Now, each scenario has its own part of a strip, or did you mean to show one strip per scenario status?

This seems a bit confusing to me, I would prefer scenarios colors to be descriptive of their status (as now)

**Comment by fpokryvk** [comment]
> * line: Feature foo -- total -- executed -- progress bar (passed green/failed red/skipped grey...)|====70%====......| -- elapsed time: N min M sec -- some other metrics/utilities(1)

What is the meaning of "70%"? Is it success rate? Also, that seems to much info for single line.

(1) - we can add API for that, the question is how usefull would that be and how to format it.
```python
def before_feature(context, feature):
   formatter = [f for f in context._runner.formatters if "html-pretty" if f.name][0]
   fomratter.current_feature.set_addotional_data({"OS": "ubuntu", "RAM":"4GB", "Disk Free": "14,7GB"})
```

Making goto is no problem, since each scenario has its id in form `fX-sY`, it is enough to add `<a href="#fX-sY">...</a>`.

Also, we usually have single-scenario reports, and this data are not relevant in that case, so I would make there condition to show it only if there are multiple features. The same for per-feature summary, if it is single scenario feature, I would collapse it by default, otherwise leave it opened.

Regarding the title (that is from `behave.ini` or can be later overridden by `formatter.set_title()`), I would show it only if additional info is present in `behave.ini`, or it is explicitly set in `behave.ini` to be shown.

**Comment by fpokryvk** [comment]
> This seems a bit confusing to me, I would prefer scenarios colors to be descriptive of their status (as now)

My idea was to show scenarios by their duration, so some long lasting scenarios would stick out (might be interesting to have such measure). See the updated screenshot in next comment.

However, this needs to wait when my colleague comes back in new year, so we can discuss new features like this.

**Comment by lu-maca** [comment]
> What is the meaning of "70%"? Is it success rate?

70% was only an example to say that I would add the percentage of passed. 

>  Also, that seems to much info for single line.

Yesterday I found [this](https://github.com/hrcorval/behavex) project, from which my suggestions about the "feature summary". In my opinion, when you have multiple features in a single report (and this is what we have currently) it could be useful to navigate in the file and to have the "big picture" at a beginning of the page.

> (1) - we can add API for that, the question is how usefull would that be and how to format it.

I can give an example about how I thought it (it may be a very personal usage, so probably it's not the best example): suppose I write a feature file for a functionality which is based on N requirements, I would then add the tested requirements ID to that "customizable" field.
Another example that I'm thinking about is to give the possibility to add buttons that do something (for example, if a scenario fails, I would like to open a github/Jira issue/ticket related to the problem).

> However, this needs to wait when my colleague comes back in new year, so we can discuss new features like this.

No problem, all this work that you are doing is really appreciated! :)

**Comment by fpokryvk** [comment]
BehaveX report looks good. Sure we can add similar summary table of features, in case there are multiple features (for single feature, that can be seen directly in feature summary). I will wait for my colleague to discuss and merge what we have open now, then we can discuss this, as it will be bigger change, that will need testing.

**Comment by fpokryvk** [comment]
Discussion in this issue diverged a bit. Original issue was about summary of single feature, which will be fixed in the next release. There is new issue to track the discussed changes #26.
